version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "db"
    # ports:
    #   - "8000:8000"
    # command: php artisan serve --host=0.0.0.0 --port=8000
  db:
    image: mysql:5.6
    volumes:
      - ./volumes:/var/lib/mysql
    ports:
      - "3452:5432"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: loki
      MYSQL_USER: loki
      MYSQL_PASSWORD: 123456
  webserver:
    image: nginx
    ports:
      - "8888:80"
    volumes:
      - .:/app
      - ./docker-config/nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - app